import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { getIosElements, getIosModuleClassNames } from '../common/config';
import { discoverModules, type DiscoveredModule } from '../common/discoverModules';
import { getDedupedAndroidModuleClassNames } from '../common/generateExtCode';
import { resolveHostPaths, type IosUrlSchemeConfig } from '../common/hostConfig';
import { buildHostNativeModulesManifestJson, TAMER_HOST_NATIVE_MODULES_FILENAME } from '../common/hostNativeModulesManifest';
import { addResourceToXcodeProject } from './syncHost';
import syncHostIos from './syncHost';

export type IosAutolinkSyncOpts = {
    release?: boolean;
    includeDevClient?: boolean;
};

const autolink = (syncHostOpts?: IosAutolinkSyncOpts) => {
    let resolved: ReturnType<typeof resolveHostPaths>;
    try {
        resolved = resolveHostPaths();
    } catch (error: any) {
        console.error(`❌ Error loading configuration: ${error.message}`);
        process.exit(1);
    }

    const projectRoot = resolved.projectRoot;
    const iosProjectPath = resolved.iosDir;

    // --- Core Logic ---

    function updateGeneratedSection(filePath: string, newContent: string, startMarker: string, endMarker: string): void {
        if (!fs.existsSync(filePath)) {
            console.warn(`⚠️ File not found, skipping update: ${filePath}`);
            return;
        }

        let fileContent = fs.readFileSync(filePath, 'utf8');
        const escapedStartMarker = startMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const escapedEndMarker = endMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

        const regex = new RegExp(`${escapedStartMarker}[\\s\\S]*?${escapedEndMarker}`, 'g');
        const replacementBlock = `${startMarker}\n${newContent}\n${endMarker}`;

        if (regex.test(fileContent)) {
            // Remove all existing generated blocks first to avoid creating duplicates,
            // then insert a single replacement at the position of the first found start marker.
            const firstStartIdx = fileContent.indexOf(startMarker);
            // Remove all occurrences
            fileContent = fileContent.replace(regex, '');

            if (firstStartIdx !== -1) {
                const before = fileContent.slice(0, firstStartIdx);
                const after = fileContent.slice(firstStartIdx);
                fileContent = `${before}${replacementBlock}${after}`;
            } else {
                // Fallback: append at end
                fileContent += `\n${replacementBlock}\n`;
            }
        } else {
            // If markers aren't present at all — append at end and warn so user can add markers to control placement.
            console.warn(`⚠️ Could not find autolink markers in ${path.basename(filePath)}. Appending to the end of the file.`);
            fileContent += `\n${replacementBlock}\n`;
        }

        fs.writeFileSync(filePath, fileContent, 'utf8');
        console.log(`✅ Updated autolinked section in ${path.basename(filePath)}`);
    }

    function resolvePodDirectory(pkg: DiscoveredModule): string {
        const configuredDir = path.join(pkg.packagePath, pkg.config.ios?.podspecPath || '.');
        if (fs.existsSync(configuredDir)) {
            return configuredDir;
        }

        const iosDir = path.join(pkg.packagePath, 'ios');
        if (fs.existsSync(iosDir)) {
            const stack = [iosDir];
            while (stack.length > 0) {
                const current = stack.pop()!;
                try {
                    const entries = fs.readdirSync(current, { withFileTypes: true });
                    const podspec = entries.find((entry) => entry.isFile() && entry.name.endsWith('.podspec'));
                    if (podspec) {
                        return current;
                    }
                    for (const entry of entries) {
                        if (entry.isDirectory()) {
                            stack.push(path.join(current, entry.name));
                        }
                    }
                } catch {
                    // Ignore unreadable directories and keep searching.
                }
            }
        }

        return configuredDir;
    }

    function resolvePodName(pkg: DiscoveredModule): string {
        const fullPodspecDir = resolvePodDirectory(pkg);
        if (fs.existsSync(fullPodspecDir)) {
            try {
                const files = fs.readdirSync(fullPodspecDir);
                const podspecFile = files.find(f => f.endsWith('.podspec'));
                if (podspecFile) return podspecFile.replace('.podspec', '');
            } catch { /* fall through */ }
        }
        return pkg.name.split('/').pop()!.replace(/-/g, '');
    }

    function updatePodfile(packages: DiscoveredModule[]): void {
        const podfilePath = path.join(iosProjectPath, 'Podfile');
        let scriptContent = `  # This section is automatically generated by Tamer4Lynx.\n  # Manual edits will be overwritten.`;

        const iosPackages = packages.filter(p => p.config.ios);

        if (iosPackages.length > 0) {
            iosPackages.forEach(pkg => {
                const relativePath = path.relative(iosProjectPath, resolvePodDirectory(pkg));
                const podName = resolvePodName(pkg);
                scriptContent += `\n  pod '${podName}', :path => '${relativePath}'`;
            });
        } else {
            scriptContent += `\n  # No native modules found by Tamer4Lynx autolinker.`;
        }

        updateGeneratedSection(podfilePath, scriptContent.trim(), '# GENERATED AUTOLINK DEPENDENCIES START', '# GENERATED AUTOLINK DEPENDENCIES END');
    }

    function ensureXElementPod(): void {
        const podfilePath = path.join(iosProjectPath, 'Podfile');
        if (!fs.existsSync(podfilePath)) return;
        let content = fs.readFileSync(podfilePath, 'utf8');
        if (content.includes("pod 'XElement'")) return;

        const lynxVersionMatch = content.match(/pod\s+'Lynx',\s*'([^']+)'/);
        const lynxVersion = lynxVersionMatch?.[1] ?? '3.6.0';
        const xelementBlock = `  pod 'XElement', '${lynxVersion}'\n\n  `;

        if (content.includes('# GENERATED AUTOLINK DEPENDENCIES START')) {
            content = content.replace(
                /(# GENERATED AUTOLINK DEPENDENCIES START)/,
                `${xelementBlock}$1`
            );
        } else {
            const insertAfter = /pod\s+'LynxService'[^\n]*(?:\n\s*'[^']*',?\s*)*/;
            const serviceMatch = content.match(insertAfter);
            if (serviceMatch) {
                const idx = serviceMatch.index! + serviceMatch[0].length;
                content = content.slice(0, idx) + `\n  pod 'XElement', '${lynxVersion}'` + content.slice(idx);
            } else {
                content += `\n  pod 'XElement', '${lynxVersion}'\n`;
            }
        }
        fs.writeFileSync(podfilePath, content, 'utf8');
        console.log(`✅ Added XElement pod (v${lynxVersion}) to Podfile`);
    }

    function ensureLynxDevToolPods(packages: DiscoveredModule[]): void {
        const hasDevClient = packages.some(
            (p) => p.name === '@tamer4lynx/tamer-dev-client' || p.name === 'tamer-dev-client',
        );
        if (!hasDevClient) return;

        const podfilePath = path.join(iosProjectPath, 'Podfile');
        if (!fs.existsSync(podfilePath)) return;
        let content = fs.readFileSync(podfilePath, 'utf8');
        if (content.includes("pod 'LynxDevtool'") || content.includes('pod "LynxDevtool"')) return;

        const lynxVersionMatch = content.match(/pod\s+'Lynx',\s*'([^']+)'/);
        const lynxVersion = lynxVersionMatch?.[1] ?? '3.6.0';

        if (!content.includes("'Devtool'") && !content.includes('"Devtool"')) {
            content = content.replace(
                /(\s+'Http',\s*\n)(\s*\])/,
                "$1    'Devtool',\n$2",
            );
        }

        const devtoolLine = `  pod 'LynxDevtool', '${lynxVersion}'\n\n  `;
        if (content.includes('# GENERATED AUTOLINK DEPENDENCIES START')) {
            content = content.replace(/(# GENERATED AUTOLINK DEPENDENCIES START)/, `${devtoolLine}$1`);
        } else {
            const insertAfter = /pod\s+'LynxService'[^\n]*(?:\n\s*'[^']*',?\s*)*\]\s*/;
            const serviceMatch = content.match(insertAfter);
            if (serviceMatch) {
                const idx = serviceMatch.index! + serviceMatch[0].length;
                content = content.slice(0, idx) + `\n  pod 'LynxDevtool', '${lynxVersion}'` + content.slice(idx);
            } else {
                content += `\n  pod 'LynxDevtool', '${lynxVersion}'\n`;
            }
        }
        fs.writeFileSync(podfilePath, content, 'utf8');
        console.log(`✅ Added Lynx DevTool pods (v${lynxVersion}) to Podfile`);
    }

    function ensureLynxPatchInPodfile(): void {
        const podfilePath = path.join(iosProjectPath, 'Podfile');
        if (!fs.existsSync(podfilePath)) return;
        let content = fs.readFileSync(podfilePath, 'utf8');
        if (content.includes("content.gsub(/\\btypeof\\(/, '__typeof__(')")) return;
        const patch = `
  Dir.glob(File.join(installer.sandbox.root, 'Lynx/platform/darwin/**/*.{m,mm}')).each do |lynx_source|
    next unless File.file?(lynx_source)
    content = File.read(lynx_source)
    next unless content.match?(/\\btypeof\\(/)
    File.chmod(0644, lynx_source) rescue nil
    File.write(lynx_source, content.gsub(/\\btypeof\\(/, '__typeof__('))
  end`;
        content = content.replace(/(\n  end\s*\n)(end\s*)$/, `$1${patch}\n$2`);
        fs.writeFileSync(podfilePath, content, 'utf8');
        console.log('✅ Added Lynx typeof patch to Podfile post_install.');
    }

    function ensurePodBuildSettings(): void {
        const podfilePath = path.join(iosProjectPath, 'Podfile');
        if (!fs.existsSync(podfilePath)) return;
        let content = fs.readFileSync(podfilePath, 'utf8');

        let changed = false;
        if (!content.includes('CLANG_ENABLE_EXPLICIT_MODULES')) {
            content = content.replace(
                /config\.build_settings\['IPHONEOS_DEPLOYMENT_TARGET'\]\s*=\s*'[^']*'/,
                `$&\n      config.build_settings['CLANG_ENABLE_EXPLICIT_MODULES'] = 'NO'\n      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'`
            );
            changed = true;
        }

        if (!content.includes("gsub('-Werror'")) {
            const xcconfigStrip = `
  Dir.glob(File.join(installer.sandbox.root, 'Target Support Files', 'Lynx', '*.xcconfig')).each do |xcconfig_path|
    next unless File.file?(xcconfig_path)
    content = File.read(xcconfig_path)
    next unless content.include?('-Werror')
    File.write(xcconfig_path, content.gsub('-Werror', ''))
  end`;
            content = content.replace(
                /(Dir\.glob.*?Lynx\/platform\/darwin)/s,
                `${xcconfigStrip}\n  $1`
            );
            changed = true;
        }

        if (!content.includes("target.name == 'PrimJS'") && content.includes("target.name == 'Lynx'")) {
            const primjsBlock = `
    if target.name == 'PrimJS'
      target.build_configurations.each do |config|
        config.build_settings['OTHER_CFLAGS'] = "$(inherited) -Wno-macro-redefined"
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = "$(inherited) -Wno-macro-redefined"
      end
    end`;
            content = content.replace(
                /(    end)\n(  end)\n(  Dir\.glob\(File\.join\(installer\.sandbox\.root,\s*'Target Support Files',\s*'Lynx')/,
                `$1${primjsBlock}\n  $2\n  $3`
            );
            changed = true;
        }

        if (changed) {
            fs.writeFileSync(podfilePath, content, 'utf8');
            console.log('✅ Added Xcode compatibility build settings to Podfile post_install.');
        }
    }

    /**
     * Update LynxInitProcessor.swift with module registrations.
     * Emits runtime-safe registrations using NSClassFromString to avoid compile-time
     * dependency issues when modules are provided by CocoaPods.
     */
    function updateLynxInitProcessor(packages: DiscoveredModule[]): void {
        const appNameFromConfig = resolved.config.ios?.appName;
        const candidatePaths: string[] = [];
        if (appNameFromConfig) {
            candidatePaths.push(path.join(iosProjectPath, appNameFromConfig, 'LynxInitProcessor.swift'));
        }
        candidatePaths.push(path.join(iosProjectPath, 'LynxInitProcessor.swift'));

        const found = candidatePaths.find(p => fs.existsSync(p));
        const lynxInitPath: string = (found ?? candidatePaths[0]) as string;

        const iosPackages = packages.filter(p => getIosModuleClassNames(p.config.ios).length > 0 || Object.keys(getIosElements(p.config.ios)).length > 0);

        // --- Deduplicate: compute which packages contribute unique registrations ---
        const seenModules = new Set<string>();
        const seenElements = new Set<string>();
        const packagesWithContributions = new Set<DiscoveredModule>();

        for (const pkg of iosPackages) {
            let hasUnique = false;
            for (const cls of getIosModuleClassNames(pkg.config.ios)) {
                if (!seenModules.has(cls)) {
                    seenModules.add(cls);
                    hasUnique = true;
                } else {
                    console.warn(`⚠️ Skipping duplicate module "${cls}" from ${pkg.name} (already registered by another package)`);
                }
            }
            for (const tag of Object.keys(getIosElements(pkg.config.ios))) {
                if (!seenElements.has(tag)) {
                    seenElements.add(tag);
                    hasUnique = true;
                } else {
                    console.warn(`⚠️ Skipping duplicate element "${tag}" from ${pkg.name} (already registered by another package)`);
                }
            }
            if (hasUnique) packagesWithContributions.add(pkg);
        }

        const importPackages = iosPackages.filter(p => packagesWithContributions.has(p));

        // --- Generate import statements for discovered native packages ---
        function updateImportsSection(filePath: string, pkgs: DiscoveredModule[]) {
            const startMarker = '// GENERATED IMPORTS START';
            const endMarker = '// GENERATED IMPORTS END';

            if (pkgs.length === 0) {
                const placeholder = '// No native imports found by Tamer4Lynx autolinker.';
                updateGeneratedSection(filePath, placeholder, startMarker, endMarker);
                return;
            }

            const imports = pkgs.map(pkg => {
                const podName = resolvePodName(pkg);
                return `import ${podName}`;
            }).join('\n');

            const fileContent = fs.readFileSync(filePath, 'utf8');
            if (fileContent.indexOf(startMarker) !== -1) {
                updateGeneratedSection(filePath, imports, startMarker, endMarker);
                return;
            }

            const importRegex = /^(import\s+[^\r\n]+)\r?\n/gm;
            let match: RegExpExecArray | null = null;
            let lastMatchEnd = -1;
            while ((match = importRegex.exec(fileContent)) !== null) {
                lastMatchEnd = importRegex.lastIndex;
            }

            const block = `${startMarker}\n${imports}\n${endMarker}`;
            let newContent: string;

            if (lastMatchEnd !== -1) {
                const before = fileContent.slice(0, lastMatchEnd);
                const after = fileContent.slice(lastMatchEnd);
                newContent = `${before}\n${block}\n${after}`;
            } else {
                const foundationIdx = fileContent.indexOf('import Foundation');
                if (foundationIdx !== -1) {
                    const lineEnd = fileContent.indexOf('\n', foundationIdx);
                    const insertPos = lineEnd !== -1 ? lineEnd + 1 : foundationIdx + 'import Foundation'.length;
                    const before = fileContent.slice(0, insertPos);
                    const after = fileContent.slice(insertPos);
                    newContent = `${before}\n${block}\n${after}`;
                } else {
                    newContent = `${block}\n\n${fileContent}`;
                }
            }

            fs.writeFileSync(filePath, newContent, 'utf8');
            console.log(`✅ Updated imports in ${path.basename(filePath)}`);
        }

        updateImportsSection(lynxInitPath, importPackages);

        if (importPackages.length === 0) {
            const placeholder = '        // No native modules found by Tamer4Lynx autolinker.';
            updateGeneratedSection(lynxInitPath, placeholder, '// GENERATED AUTOLINK START', '// GENERATED AUTOLINK END');
        } else {
        const seenModules2 = new Set<string>();
        const seenElements2 = new Set<string>();

        const blocks = importPackages.flatMap((pkg) => {
            const classNames = getIosModuleClassNames(pkg.config.ios);
            const moduleBlocks = classNames.filter((cls) => {
                if (seenModules2.has(cls)) return false;
                seenModules2.add(cls);
                return true;
            }).map((classNameRaw) => [
                `        // Register module from package: ${pkg.name}`,
                `        globalConfig.register(${classNameRaw}.self)`,
            ].join('\n'));
            const elementBlocks = Object.entries(getIosElements(pkg.config.ios)).filter(([tagName]) => {
                if (seenElements2.has(tagName)) return false;
                seenElements2.add(tagName);
                return true;
            }).map(([tagName, classNameRaw]) => [
                `        // Register element from package: ${pkg.name}`,
                `        globalConfig.registerUI(${classNameRaw}.self, withName: "${tagName}")`,
            ].join('\n'));
            return [...moduleBlocks, ...elementBlocks];
        });

        const content = blocks.join('\n\n');
        updateGeneratedSection(lynxInitPath, content, '// GENERATED AUTOLINK START', '// GENERATED AUTOLINK END');
        }

        const hasDevClient = packages.some((p) => p.name === '@tamer4lynx/tamer-dev-client');
        const androidNames = getDedupedAndroidModuleClassNames(packages);
        let devClientSupportedBody: string;
        if (hasDevClient && androidNames.length > 0) {
            devClientSupportedBody = `        DevClientModule.attachSupportedModuleClassNames([\n${androidNames.map((n) => `            "${n.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`).join(',\n')}\n        ])`;
        } else if (hasDevClient) {
            devClientSupportedBody = '        DevClientModule.attachSupportedModuleClassNames([])';
        } else {
            devClientSupportedBody = '        // @tamer4lynx/tamer-dev-client not linked';
        }
        if (fs.readFileSync(lynxInitPath, 'utf8').includes('GENERATED DEV_CLIENT_SUPPORTED START')) {
            updateGeneratedSection(lynxInitPath, devClientSupportedBody, '// GENERATED DEV_CLIENT_SUPPORTED START', '// GENERATED DEV_CLIENT_SUPPORTED END');
        }
    }

    function findInfoPlist(): string | null {
        const appNameFromConfig = resolved.config.ios?.appName;
        const candidates: string[] = [];
        if (appNameFromConfig) {
            candidates.push(path.join(iosProjectPath, appNameFromConfig, 'Info.plist'));
        }
        candidates.push(path.join(iosProjectPath, 'Info.plist'));

        return candidates.find(p => fs.existsSync(p)) ?? null;
    }

    function readPlistXml(plistPath: string): string {
        return fs.readFileSync(plistPath, 'utf8');
    }

    function syncInfoPlistPermissions(packages: DiscoveredModule[]): void {
        const plistPath = findInfoPlist();
        if (!plistPath) return;

        const allPermissions: Record<string, string> = {};
        for (const pkg of packages) {
            const iosPerms = pkg.config.ios?.iosPermissions;
            if (iosPerms) {
                for (const [key, desc] of Object.entries(iosPerms)) {
                    if (!allPermissions[key]) {
                        allPermissions[key] = desc;
                    }
                }
            }
        }
        if (Object.keys(allPermissions).length === 0) return;

        let plist = readPlistXml(plistPath);

        let added = 0;
        for (const [key, desc] of Object.entries(allPermissions)) {
            if (plist.includes(`<key>${key}</key>`)) continue;

            const insertion = `\t<key>${key}</key>\n\t<string>${desc}</string>\n`;
            plist = plist.replace(
                /(<\/dict>\s*<\/plist>)/,
                `${insertion}$1`
            );
            added++;
        }

        if (added > 0) {
            fs.writeFileSync(plistPath, plist, 'utf8');
            console.log(`✅ Synced ${added} Info.plist permission description(s)`);
        }
    }

    function syncInfoPlistUrlSchemes(): void {
        const urlSchemes = resolved.config.ios?.urlSchemes;
        if (!urlSchemes || urlSchemes.length === 0) return;

        const plistPath = findInfoPlist();
        if (!plistPath) return;

        let plist = readPlistXml(plistPath);

        const schemesXml = urlSchemes.map((s: IosUrlSchemeConfig) => {
            const role = s.role ?? 'Editor';
            return `\t\t\t<dict>
\t\t\t\t<key>CFBundleTypeRole</key>
\t\t\t\t<string>${role}</string>
\t\t\t\t<key>CFBundleURLSchemes</key>
\t\t\t\t<array>
\t\t\t\t\t<string>${s.scheme}</string>
\t\t\t\t</array>
\t\t\t</dict>`;
        }).join('\n');

        const generatedBlock = `\t<key>CFBundleURLTypes</key>
\t<array>
\t\t<!-- GENERATED URL SCHEMES START -->
${schemesXml}
\t\t<!-- GENERATED URL SCHEMES END -->
\t</array>`;

        const startMarker = '<!-- GENERATED URL SCHEMES START -->';
        const endMarker = '<!-- GENERATED URL SCHEMES END -->';

        if (plist.includes(startMarker) && plist.includes(endMarker)) {
            const regex = new RegExp(
                `${startMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${endMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`,
                'g'
            );
            plist = plist.replace(regex, `${startMarker}\n${schemesXml}\n\t\t${endMarker}`);
        } else if (plist.includes('<key>CFBundleURLTypes</key>')) {
            console.log('ℹ️ CFBundleURLTypes exists but has no generated markers. Skipping URL scheme sync.');
            return;
        } else {
            plist = plist.replace(
                /(<\/dict>\s*<\/plist>)/,
                `${generatedBlock}\n$1`
            );
        }

        fs.writeFileSync(plistPath, plist, 'utf8');
        console.log(`✅ Synced ${urlSchemes.length} iOS URL scheme(s) into Info.plist`);
    }

    function runPodInstall(forcePath?: string) {
        const podfilePath = forcePath ?? path.join(iosProjectPath, 'Podfile');
        if (!fs.existsSync(podfilePath)) {
            console.log('ℹ️ No Podfile found in ios directory; skipping `pod install`.');
            return;
        }

        const cwd = path.dirname(podfilePath);
        try {
            console.log(`ℹ️ Running ` + '`pod install`' + ` in ${cwd}...`);
            try {
                execSync('pod install', { cwd, stdio: 'inherit' });
            } catch {
                console.log('ℹ️ Retrying `pod install` with repo update...');
                execSync('pod install --repo-update', { cwd, stdio: 'inherit' });
            }
            console.log('✅ `pod install` completed successfully.');
        } catch (e: any) {
            console.warn(`⚠️ 'pod install' failed: ${e.message}`);
            console.log('⚠️ You can run `pod install` manually in the ios directory.');
        }
    }

    // --- Main Execution ---
    function run() {
        console.log('🔎 Finding Lynx extension packages (lynx.ext.json / tamer.json)...');
        const packages = discoverModules(projectRoot).filter((p) => p.config.ios);

        if (packages.length > 0) {
            console.log(`Found ${packages.length} package(s): ${packages.map(p => p.name).join(', ')}`);
        } else {
            console.log('ℹ️ No Tamer4Lynx native packages found.');
        }

        syncHostIos(syncHostOpts);
        updatePodfile(packages);
        ensureXElementPod();
        ensureLynxDevToolPods(discoverModules(projectRoot));
        ensureLynxPatchInPodfile();
        ensurePodBuildSettings();
        updateLynxInitProcessor(packages);
        writeHostNativeModulesManifest();
        syncInfoPlistPermissions(packages);
        syncInfoPlistUrlSchemes();

        const appNameFromConfig = resolved.config.ios?.appName;
        if (appNameFromConfig) {
            const appPodfile = path.join(iosProjectPath, appNameFromConfig, 'Podfile');
            if (fs.existsSync(appPodfile)) {
                runPodInstall(appPodfile);
                console.log('✨ Autolinking complete for iOS.');
                return;
            }
        }

        runPodInstall();
        console.log('✨ Autolinking complete for iOS.');
    }

    function writeHostNativeModulesManifest(): void {
        const allPkgs = discoverModules(projectRoot);
        const hasDevClient = allPkgs.some((p) => p.name === '@tamer4lynx/tamer-dev-client');
        const appFolder = resolved.config.ios?.appName;
        if (!hasDevClient || !appFolder) return;
        const androidNames = getDedupedAndroidModuleClassNames(allPkgs);
        const appDir = path.join(iosProjectPath, appFolder);
        fs.mkdirSync(appDir, { recursive: true });
        const manifestPath = path.join(appDir, TAMER_HOST_NATIVE_MODULES_FILENAME);
        fs.writeFileSync(manifestPath, buildHostNativeModulesManifestJson(androidNames), 'utf8');
        console.log(`✅ Wrote ${TAMER_HOST_NATIVE_MODULES_FILENAME} (native module ids for dev-client checks)`);
        const pbxprojPath = path.join(iosProjectPath, `${appFolder}.xcodeproj`, 'project.pbxproj');
        if (fs.existsSync(pbxprojPath)) {
            addResourceToXcodeProject(pbxprojPath, appFolder, TAMER_HOST_NATIVE_MODULES_FILENAME);
        }
    }

    run();
}

export default autolink;