import fs from 'fs';
import path from 'path';
import { discoverModules, type DiscoveredModule } from '../common/discoverModules';
import { generateActivityLifecycleKotlin, generateLynxExtensionsKotlin } from '../common/generateExtCode';
import { resolveHostPaths, type DeepLinkConfig } from '../common/hostConfig';
import type { NormalizedExtensionConfig } from '../common/config';

const TAMER_DEV_CLIENT_FALLBACK: DiscoveredModule = {
    name: '@tamer4lynx/tamer-dev-client',
    packagePath: '',
    config: {
        android: {
            moduleClassName: 'com.nanofuxion.tamerdevclient.DevClientModule',
            sourceDir: 'android',
            permissions: ['CAMERA', 'ACCESS_NETWORK_STATE', 'ACCESS_WIFI_STATE'],
        },
    } as NormalizedExtensionConfig,
};

const REQUIRED_CATALOG_ENTRIES: Record<string, { versionRef: string; version: string; libraryKey: string; libraryLine: string }> = {
    'androidx.biometric': {
        versionRef: 'biometric',
        version: '1.1.0',
        libraryKey: 'androidx-biometric',
        libraryLine: 'androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }',
    },
};

const REQUIRED_PLUGIN_ENTRIES: Record<string, { pluginKey: string; pluginLine: string }> = {
    'android.library': {
        pluginKey: 'android-library',
        pluginLine: 'android-library = { id = "com.android.library", version.ref = "agp" }',
    },
    'kotlin.compose': {
        pluginKey: 'kotlin-compose',
        pluginLine: 'kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }',
    },
};

const autolink = (opts?: { includeDevClient?: boolean }) => {
    let resolved: ReturnType<typeof resolveHostPaths>;
    try {
        resolved = resolveHostPaths();
        if (!resolved.config.android?.packageName) {
            throw new Error('"android.packageName" must be defined in tamer.config.json');
        }
    } catch (error: any) {
        console.error(`❌ Error loading configuration: ${error.message}`);
        process.exit(1);
    }

    const { androidDir: appAndroidPath, config } = resolved;
    const packageName = config.android!.packageName!;
    const projectRoot = resolved.projectRoot;

    // --- Core Logic ---

    /**
     * Replaces the content of a file between specified start and end markers.
     * @param filePath The path to the file to update.
     * @param newContent The new content to insert between the markers.
     * @param startMarker The starting delimiter.
     * @param endMarker The ending delimiter.
     */
    function updateGeneratedSection(filePath: string, newContent: string, startMarker: string, endMarker: string): void {
        if (!fs.existsSync(filePath)) {
            console.warn(`⚠️ File not found, skipping update: ${filePath}`);
            return;
        }

        let fileContent = fs.readFileSync(filePath, 'utf8');
        // Escape special characters in markers for RegExp
        const escapedStartMarker = startMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const escapedEndMarker = endMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

        const regex = new RegExp(`${escapedStartMarker}[\\s\\S]*?${escapedEndMarker}`, 'g');
        const replacementBlock = `${startMarker}\n${newContent}\n${endMarker}`;

        if (regex.test(fileContent)) {
            fileContent = fileContent.replace(regex, replacementBlock);
        } else {
            console.warn(`⚠️ Could not find autolink markers in ${path.basename(filePath)}. Appending to the end of the file.`);
            fileContent += `\n${replacementBlock}\n`;
        }

        fs.writeFileSync(filePath, fileContent);
        console.log(`✅ Updated autolinked section in ${path.basename(filePath)}`);
    }

    /**
     * Generates the Gradle settings script content and updates settings.gradle.kts.
     * @param packages The list of discovered native packages.
     */
    function updateSettingsGradle(packages: DiscoveredModule[]): void {
        const settingsFilePath = path.join(appAndroidPath, 'settings.gradle.kts');
        let scriptContent = `// This section is automatically generated by Tamer4Lynx.\n// Manual edits will be overwritten.`;

        const androidPackages = packages.filter(p => p.config.android);

        if (androidPackages.length > 0) {
            androidPackages.forEach(pkg => {
                const gradleProjectName = pkg.name.replace(/^@/, '').replace(/\//g, '_');
                const sourceDir = pkg.config.android?.sourceDir || 'android';
                const projectPath = path.resolve(pkg.packagePath, sourceDir).replace(/\\/g, '/');

                scriptContent += `\ninclude(":${gradleProjectName}")`;
                scriptContent += `\nproject(":${gradleProjectName}").projectDir = file("${projectPath}")`;
            });
        } else {
            scriptContent += `\nprintln("No native modules found by Tamer4Lynx autolinker.")`;
        }

        updateGeneratedSection(settingsFilePath, scriptContent.trim(), '// GENERATED AUTOLINK START', '// GENERATED AUTOLINK END');
    }

    /**
     * Generates the app-level dependencies and updates app/build.gradle.kts.
     * @param packages The list of discovered native packages.
     */
    function updateAppBuildGradle(packages: DiscoveredModule[]) {
        const appBuildGradlePath = path.join(appAndroidPath, 'app', 'build.gradle.kts');
        const androidPackages = packages.filter(p => p.config.android);

        const implementationLines = androidPackages
            .map(p => {
                // Sanitize package name for Gradle: @org/name -> org_name
                const gradleProjectName = p.name.replace(/^@/, '').replace(/\//g, '_');
                return `    implementation(project(":${gradleProjectName}"))`;
            })
            .join('\n');

        const scriptContent = `// This section is automatically generated by Tamer4Lynx.\n    // Manual edits will be overwritten.\n${implementationLines || '    // No native dependencies found to link.'}`;

        updateGeneratedSection(
            appBuildGradlePath,
            scriptContent,
            '// GENERATED AUTOLINK DEPENDENCIES START',
            '// GENERATED AUTOLINK DEPENDENCIES END'
        );
    }

    function generateKotlinExtensionsFile(packages: DiscoveredModule[], projectPackage: string): void {
        const packagePath = projectPackage.replace(/\./g, '/');
        const generatedDir = path.join(appAndroidPath, 'app', 'src', 'main', 'kotlin', packagePath, 'generated');
        const kotlinExtensionsPath = path.join(generatedDir, 'GeneratedLynxExtensions.kt');
        const content = `/**
 * This file is generated by the Tamer4Lynx autolinker.
 * Do not edit this file manually.
 */
${generateLynxExtensionsKotlin(packages, projectPackage)}`;
        fs.mkdirSync(generatedDir, { recursive: true });
        fs.writeFileSync(kotlinExtensionsPath, content.trimStart());
        console.log(`✅ Generated Kotlin extensions at ${kotlinExtensionsPath}`);
    }

    function generateActivityLifecycleFile(packages: DiscoveredModule[], projectPackage: string): void {
        const packageKotlinPath = projectPackage.replace(/\./g, '/');
        const generatedDir = path.join(appAndroidPath, 'app', 'src', 'main', 'kotlin', packageKotlinPath, 'generated');
        const outputPath = path.join(generatedDir, 'GeneratedActivityLifecycle.kt');
        const content = `/**
 * This file is generated by the Tamer4Lynx autolinker.
 * Do not edit this file manually.
 */
${generateActivityLifecycleKotlin(packages, projectPackage)}`;
        fs.mkdirSync(generatedDir, { recursive: true });
        fs.writeFileSync(outputPath, content);
        console.log(`✅ Generated activity lifecycle patches at ${outputPath}`);
    }

    /**
     * Merges deep link intent filters from the host tamer.config.json into AndroidManifest.xml
     * between <!-- GENERATED DEEP LINKS START --> and <!-- GENERATED DEEP LINKS END --> markers.
     */
    function syncDeepLinkIntentFilters(): void {
        const deepLinks = config.android?.deepLinks;
        if (!deepLinks || deepLinks.length === 0) return;

        const manifestPath = path.join(appAndroidPath, 'app', 'src', 'main', 'AndroidManifest.xml');
        if (!fs.existsSync(manifestPath)) return;

        const intentFilters = deepLinks.map((link: DeepLinkConfig) => {
            const dataAttrs = [
                `android:scheme="${link.scheme}"`,
                link.host ? `android:host="${link.host}"` : '',
                link.pathPrefix ? `android:pathPrefix="${link.pathPrefix}"` : '',
            ].filter(Boolean).join(' ');
            return `        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data ${dataAttrs} />
        </intent-filter>`;
        }).join('\n');

        updateGeneratedSection(
            manifestPath,
            intentFilters,
            '        <!-- GENERATED DEEP LINKS START -->',
            '        <!-- GENERATED DEEP LINKS END -->'
        );
    }

    // --- Main Execution ---

    function run() {
        console.log('🔎 Finding Lynx extension packages (lynx.ext.json / tamer.json)...');
        let packages = discoverModules(projectRoot).filter((p) => p.config.android);

        const includeDevClient = opts?.includeDevClient === true;
        const devClientScoped = path.join(projectRoot, 'node_modules', '@tamer4lynx', 'tamer-dev-client');
        const devClientFlat = path.join(projectRoot, 'node_modules', 'tamer-dev-client');
        const devClientPath = fs.existsSync(path.join(devClientScoped, 'android')) ? devClientScoped
            : fs.existsSync(path.join(devClientFlat, 'android')) ? devClientFlat : null;
        const hasDevClient = packages.some(p => p.name === '@tamer4lynx/tamer-dev-client' || p.name === 'tamer-dev-client');

        if (includeDevClient && devClientPath && !hasDevClient) {
            packages = [{
                ...TAMER_DEV_CLIENT_FALLBACK,
                packagePath: devClientPath,
            }, ...packages];
            console.log('ℹ️ Added tamer-dev-client (fallback; lynx.ext.json missing in published package).');
        }

        if (packages.length > 0) {
            console.log(`Found ${packages.length} package(s): ${packages.map(p => p.name).join(', ')}`);
        } else {
            console.log('ℹ️ No Tamer4Lynx native packages found.');
        }

        updateSettingsGradle(packages);
        updateAppBuildGradle(packages);

        generateKotlinExtensionsFile(packages, packageName);
        generateActivityLifecycleFile(packages, packageName);

        syncManifestPermissions(packages);
        syncDeepLinkIntentFilters();
        syncVersionCatalog(packages);
        ensureXElementDeps();
        ensureReleaseSigning();

        console.log('✨ Autolinking complete.');
    }

    function syncVersionCatalog(packages: DiscoveredModule[]): void {
        const libsTomlPath = path.join(appAndroidPath, 'gradle', 'libs.versions.toml');
        if (!fs.existsSync(libsTomlPath)) return;

        const requiredAliases = new Set<string>();
        const requiredPluginAliases = new Set<string>();
        for (const pkg of packages) {
            const buildPath = path.join(pkg.packagePath, pkg.config.android?.sourceDir || 'android', 'build.gradle.kts');
            if (!fs.existsSync(buildPath)) continue;
            const content = fs.readFileSync(buildPath, 'utf8');
            for (const m of content.matchAll(/libs\.([\w.]+)/g)) {
                const alias = m[1];
                if (alias && alias in REQUIRED_CATALOG_ENTRIES) requiredAliases.add(alias);
            }
            for (const m of content.matchAll(/libs\.plugins\.([\w.]+)/g)) {
                const alias = m[1];
                if (alias && alias in REQUIRED_PLUGIN_ENTRIES) requiredPluginAliases.add(alias);
            }
        }
        if (requiredAliases.size === 0 && requiredPluginAliases.size === 0) return;

        let toml = fs.readFileSync(libsTomlPath, 'utf8');
        let updated = false;
        for (const alias of requiredAliases) {
            const entry = REQUIRED_CATALOG_ENTRIES[alias];
            if (!entry) continue;
            if (!toml.includes(`${entry.versionRef} = "`)) {
                toml = toml.replace(/(\[versions\]\n)/, `$1${entry.versionRef} = "${entry.version}"\n`);
                updated = true;
            }
            if (!toml.includes(`${entry.libraryKey} = `)) {
                toml = toml.replace(/(\[libraries\]\n)/, `$1${entry.libraryLine}\n`);
                updated = true;
            }
        }
        for (const alias of requiredPluginAliases) {
            const entry = REQUIRED_PLUGIN_ENTRIES[alias];
            if (!entry || toml.includes(`${entry.pluginKey} = `)) continue;
            toml = toml.replace(/(\[plugins\]\n)/, `$1${entry.pluginLine}\n`);
            updated = true;
        }
        if (updated) {
            fs.writeFileSync(libsTomlPath, toml);
            console.log('✅ Synced version catalog (libs.versions.toml) for linked modules.');
        }
    }

    function ensureXElementDeps(): void {
        const libsTomlPath = path.join(appAndroidPath, 'gradle', 'libs.versions.toml');
        if (fs.existsSync(libsTomlPath)) {
            let toml = fs.readFileSync(libsTomlPath, 'utf8');
            let updated = false;
            if (!toml.includes('lynx-xelement =')) {
                toml = toml.replace(
                    /(lynx-trace\s*=\s*\{[^\n]*\n)/,
                    `$1lynx-xelement = { module = "org.lynxsdk.lynx:xelement", version.ref = "lynx" }\nlynx-xelement-input = { module = "org.lynxsdk.lynx:xelement-input", version.ref = "lynx" }\n`
                );
                updated = true;
            }
            if (updated) {
                fs.writeFileSync(libsTomlPath, toml);
                console.log('✅ Added XElement entries to version catalog.');
            }
        }

        const appBuildPath = path.join(appAndroidPath, 'app', 'build.gradle.kts');
        if (fs.existsSync(appBuildPath)) {
            let content = fs.readFileSync(appBuildPath, 'utf8');
            if (!content.includes('lynx.xelement')) {
                content = content.replace(
                    /(implementation\(libs\.lynx\.service\.http\))/,
                    `$1\n    implementation(libs.lynx.xelement)\n    implementation(libs.lynx.xelement.input)`
                );
                fs.writeFileSync(appBuildPath, content);
                console.log('✅ Added XElement dependencies to app build.gradle.kts.');
            }
        }
    }

    function ensureReleaseSigning(): void {
        const appBuildPath = path.join(appAndroidPath, 'app', 'build.gradle.kts');
        if (!fs.existsSync(appBuildPath)) return;
        let content = fs.readFileSync(appBuildPath, 'utf8');
        if (content.includes('signingConfig = signingConfigs.getByName("debug")')) return;
        const releaseBlock = /(release\s*\{)([\s\S]*?)(\n        \}\s*\n(\s*\}|\s*compileOptions))/;
        const match = content.match(releaseBlock);
        if (match) {
            content = content.replace(
                releaseBlock,
                `$1$2\n            signingConfig = signingConfigs.getByName("debug")\n        $3`
            );
            fs.writeFileSync(appBuildPath, content);
            console.log('✅ Set release signing to debug so installRelease works without a keystore.');
        }
    }

    function syncManifestPermissions(packages: DiscoveredModule[]): void {
        const manifestPath = path.join(appAndroidPath, 'app', 'src', 'main', 'AndroidManifest.xml');
        if (!fs.existsSync(manifestPath)) return;

        const allPermissions = new Set<string>();
        for (const pkg of packages) {
            const perms = pkg.config.android?.permissions;
            if (Array.isArray(perms)) {
                for (const p of perms) {
                    const name = p.startsWith('android.permission.') ? p : `android.permission.${p}`;
                    allPermissions.add(name);
                }
            }
        }
        if (allPermissions.size === 0) return;

        let manifest = fs.readFileSync(manifestPath, 'utf8');
        const existingMatch = [...manifest.matchAll(/<uses-permission android:name="(android\.permission\.\w+)"\s*\/>/g)];
        const existing = new Set(existingMatch.map((m) => m[1]));
        const toAdd = [...allPermissions].filter((p) => !existing.has(p));
        if (toAdd.length === 0) return;

        const newLines = toAdd.map((p) => `    <uses-permission android:name="${p}" />`).join('\n');
        manifest = manifest.replace(
            /(\s*)(<application)/,
            `${newLines}\n$1$2`
        );
        fs.writeFileSync(manifestPath, manifest);
        console.log(`✅ Synced manifest permissions: ${toAdd.map((p) => p.split('.').pop()).join(', ')}`);
    }

    run();
}
export default autolink;