import fs from "fs";
import path from "path";
import type { HostConfig } from "./hostConfig";
import { resolveHostPaths } from "./hostConfig";
import {
  ensureTamerComponentsIncludeForProject,
  findTsconfigCandidates,
  migrateOldTamerGlobIncludes,
} from "./tsconfigUtils";

const HEADER = "// Generated by t4l — do not edit.\n";

export type AmbientTypeRef = { packageName: string; subpath: string };

function readPackageJson(pkgDir: string): {
  name?: string;
  tamer?: { ambientTypeExports?: string[] };
  exports?: Record<string, unknown>;
} | null {
  const p = path.join(pkgDir, 'package.json');
  if (!fs.existsSync(p)) return null;
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8')) as {
      name?: string;
      tamer?: { ambientTypeExports?: string[] };
      exports?: Record<string, unknown>;
    };
  } catch {
    return null;
  }
}

/** Collect ambient type export subpaths (e.g. "webview-jsx") from package.json. */
export function collectAmbientTypeExports(pkgDir: string): string[] {
  const pj = readPackageJson(pkgDir);
  if (!pj?.name?.startsWith('@tamer4lynx/')) return [];

  const explicit = pj.tamer?.ambientTypeExports;
  if (Array.isArray(explicit) && explicit.length > 0) {
    return explicit.map((s) => String(s).replace(/^\.\//, ''));
  }

  const out: string[] = [];
  const ex = pj.exports;
  if (ex && typeof ex === 'object') {
    if (typeof ex['./webview-jsx'] === 'object' || typeof ex['./webview-jsx'] === 'string') {
      out.push('webview-jsx');
    }
    if (typeof ex['./icon-jsx'] === 'object' || typeof ex['./icon-jsx'] === 'string') {
      out.push('icon-jsx');
    }
  }
  return [...new Set(out)];
}

function packageDirFromName(projectRoot: string, packageName: string): string | null {
  const parts = packageName.split("/");
  if (parts.length >= 2 && packageName.startsWith("@")) {
    const scoped = path.join(projectRoot, "node_modules", parts[0], parts[1]);
    if (fs.existsSync(path.join(scoped, "package.json"))) return scoped;
  }
  const flat = path.join(projectRoot, "node_modules", packageName);
  if (fs.existsSync(path.join(flat, "package.json"))) return flat;
  return null;
}

/** Resolved path to dist .d.ts for an export subpath (e.g. webview-jsx → dist/webview-jsx.d.ts). */
export function resolveAmbientDtsFile(pkgDir: string, subpath: string): string | null {
  const pj = readPackageJson(pkgDir);
  const key = `./${subpath}`;
  const ex = pj?.exports;
  if (ex && typeof ex === "object" && ex !== null && key in ex) {
    const entry = (ex as Record<string, unknown>)[key];
    if (entry && typeof entry === "object" && entry !== null && "types" in entry) {
      const types = (entry as { types?: string }).types;
      if (typeof types === "string") {
        const rel = types.replace(/^\.\//, "");
        const abs = path.join(pkgDir, rel);
        if (fs.existsSync(abs)) return abs;
      }
    }
  }
  const fallback = path.join(pkgDir, "dist", `${subpath}.d.ts`);
  return fs.existsSync(fallback) ? fallback : null;
}

/** Triple-slash path relative to `.tamer/tamer-components.d.ts` → ambient .d.ts file. */
export function referencePathForAmbientDts(
  projectRoot: string,
  packageName: string,
  subpath: string,
): string | null {
  const pkgDir = packageDirFromName(projectRoot, packageName);
  if (!pkgDir) return null;
  const abs = resolveAmbientDtsFile(pkgDir, subpath);
  if (!abs) return null;
  const outDir = path.join(projectRoot, ".tamer");
  let rel = path.relative(outDir, abs);
  if (!rel.startsWith(".")) {
    rel = `./${rel}`;
  }
  return rel.split(path.sep).join("/");
}

/** List refs for all installed @tamer4lynx packages under projectRoot/node_modules. */
export function listAmbientTypeRefs(projectRoot: string): AmbientTypeRef[] {
  const nm = path.join(projectRoot, 'node_modules', '@tamer4lynx');
  if (!fs.existsSync(nm)) return [];

  const refs: AmbientTypeRef[] = [];
  for (const name of fs.readdirSync(nm)) {
    const pkgDir = path.join(nm, name);
    let st: fs.Stats;
    try {
      st = fs.statSync(pkgDir);
    } catch {
      continue;
    }
    if (!st.isDirectory()) continue;
    const pj = readPackageJson(pkgDir);
    if (!pj?.name) continue;

    for (const sub of collectAmbientTypeExports(pkgDir)) {
      refs.push({ packageName: pj.name, subpath: sub });
    }
  }

  refs.sort((a, b) =>
    a.packageName === b.packageName
      ? a.subpath.localeCompare(b.subpath)
      : a.packageName.localeCompare(b.packageName),
  );
  return refs;
}

/** Write `.tamer/tamer-components.d.ts` with triple-slash path references (types= subpath does not load augmentations reliably). */
export function writeTamerComponentsDts(projectRoot: string, refs: AmbientTypeRef[]): string {
  const outDir = path.join(projectRoot, ".tamer");
  fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, "tamer-components.d.ts");

  const lines: string[] = [HEADER.trim()];
  for (const r of refs) {
    const refPath = referencePathForAmbientDts(projectRoot, r.packageName, r.subpath);
    if (refPath) {
      lines.push(`/// <reference path="${refPath}" />`);
    } else {
      lines.push(`/// <reference types="${r.packageName}/${r.subpath}" />`);
    }
  }
  const content = lines.join("\n") + "\n";
  fs.writeFileSync(outPath, content, "utf8");
  return outPath;
}

export function syncTamerComponentTypes(projectRoot: string): { outPath: string | null; refs: AmbientTypeRef[] } {
  const refs = listAmbientTypeRefs(projectRoot);
  if (refs.length === 0) {
    const outDir = path.join(projectRoot, ".tamer");
    const outPath = path.join(outDir, "tamer-components.d.ts");
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(outPath, `${HEADER.trim()}\n`, "utf8");
    return { outPath, refs: [] };
  }
  const outPath = writeTamerComponentsDts(projectRoot, refs);
  return { outPath, refs };
}

export function shouldSyncTamerComponentTypes(config: HostConfig): boolean {
  return config.syncTamerComponentTypes !== false;
}

/** Run generator + tsconfig migration/include for the current host project. */
export function runTamerComponentTypesPipeline(projectRoot?: string): void {
  const cwd = projectRoot ?? process.cwd();
  let resolved: ReturnType<typeof resolveHostPaths>;
  try {
    resolved = resolveHostPaths(cwd);
  } catch {
    return;
  }
  const { projectRoot: root, config } = resolved;
  if (!shouldSyncTamerComponentTypes(config)) return;

  syncTamerComponentTypes(root);

  const lynxRel = config.lynxProject ?? config.paths?.lynxProject;
  const lynxProject = typeof lynxRel === "string" && lynxRel.trim() ? lynxRel.trim() : undefined;

  for (const tsconfigPath of findTsconfigCandidates(root, lynxProject)) {
    if (!fs.existsSync(tsconfigPath)) continue;
    migrateOldTamerGlobIncludes(tsconfigPath);
    ensureTamerComponentsIncludeForProject(tsconfigPath, root);
  }
}
