pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "MisoCounter"
include(":app")

// GENERATED AUTOLINK START
// This section is automatically generated by Tamer4Lynx.
// Manual edits will be overwritten.
include(":tamer4lynx_jiggle")
project(":tamer4lynx_jiggle").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/jiggle/android")
include(":tamer4lynx_tamer-biometric")
project(":tamer4lynx_tamer-biometric").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-biometric/android")
include(":tamer4lynx_tamer-dev-client")
project(":tamer4lynx_tamer-dev-client").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-dev-client/android")
include(":tamer4lynx_tamer-display-browser")
project(":tamer4lynx_tamer-display-browser").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-display-browser/android")
include(":tamer4lynx_tamer-icons")
project(":tamer4lynx_tamer-icons").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-icons/android")
include(":tamer4lynx_tamer-insets")
project(":tamer4lynx_tamer-insets").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-insets/android")
include(":tamer4lynx_tamer-linking")
project(":tamer4lynx_tamer-linking").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-linking/android")
include(":tamer4lynx_tamer-local-storage")
project(":tamer4lynx_tamer-local-storage").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-local-storage/android")
include(":tamer4lynx_tamer-router")
project(":tamer4lynx_tamer-router").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-router/android")
include(":tamer4lynx_tamer-secure-store")
project(":tamer4lynx_tamer-secure-store").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-secure-store/android")
include(":tamer4lynx_tamer-system-ui")
project(":tamer4lynx_tamer-system-ui").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-system-ui/android")
include(":tamer4lynx_tamer-transports")
project(":tamer4lynx_tamer-transports").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-transports/android")
include(":tamer4lynx_tamer-webview")
project(":tamer4lynx_tamer-webview").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-webview/android")
// GENERATED AUTOLINK END
